In [1]:
import numpy as np 
import pandas as pd
import sklearn as sk

In [2]:
import pickle
X_train = pickle.load(open("X_train_smote.p", "rb"))
X_test = pickle.load(open("X_test.p", "rb"))
y_train = pickle.load(open("y_train_smote.p", "rb"))
y_test = pickle.load(open("y_test.p", "rb"))

In [3]:
X_train

number_inpatient  discharge_disposition_id  number_emergency  \
0                     0                         1                 0   
1                     1                         6                 0   
2                     0                         4                 0   
3                     2                         1                 0   
4                     0                         1                 0   
...                 ...                       ...               ...   
15707                 0                         1                 0   
15708                 2                        18                 0   
15709                 0                         1                 0   
15710                 0                         6                 0   
15711                 1                        18                 0   

       num_medications  time_in_hospital  num_lab_procedures  DXDiabetes  \
0                   13                 1                  44           0   
1                    5                 3                   2           1   
2                   19                 5                   2           0   
3                   16                 7                  29           1   
4                   23                 6                  40           0   
...                ...               ...                 ...         ...   
15707               22                 4                  39           0   
15708               17                 6                  41           1   
15709                6                 1                  29           0   
15710               24                13                  53           0   
15711                9                 2                   1           0   

       number_outpatient  DXHypertension  number_diagnoses  ...  age_20-30)  \
0                      0               0                 6  ...           0   
1                      0               1                 7  ...           0   
2                      1               0                 9  ...           0   
3                      0               0                 6  ...           0   
4                      0               1                 6  ...           0   
...                  ...             ...               ...  ...         ...   
15707                  0               0                 9  ...           0   
15708                  0               0                 9  ...           0   
15709                  0               0                 7  ...           0   
15710                  0               0                 9  ...           0   
15711                  0               0                 6  ...           0   

       admission_type_id  age_0-10)  DXFluid  age_80-90)  max_glu_serum_300  \
0                      6          0        0           1                  0   
1                      1          0        0           0                  0   
2                      2          0        0           0                  0   
3                      6          0        0           1                  0   
4                      3          0        0           0                  0   
...                  ...        ...      ...         ...                ...   
15707                  3          0        0           0                  0   
15708                  2          0        1           0                  0   
15709                  1          0        0           0                  0   
15710                  3          0        0           0                  0   
15711                  3          0        0           0                  0   

       DXPneumonia  A1Cresult_Norm  A1Cresult_8  metformin_No  
0                0               0            0             1  
1                0               0            0             1  
2                0               0            0             1  
3                0               0            0             1  
4                0     

In [4]:
X_test

number_inpatient  discharge_disposition_id  number_emergency  \
47337                 0                         6                 0   
82295                 0                         3                 0   
44783                 2                         1                 0   
84950                 0                         1                 0   
67971                 1                         3                 0   
...                 ...                       ...               ...   
60364                 0                        23                 0   
94177                 3                         1                 0   
64517                 0                         1                 0   
31907                 0                         1                 0   
8374                  0                         1                 0   

       num_medications  time_in_hospital  num_lab_procedures  DXDiabetes  \
47337               16                 1                  11           0   
82295                2                 4                   3           0   
44783               29                11                  27           0   
84950               11                 2                  37           0   
67971                8                 1                  45           0   
...                ...               ...                 ...         ...   
60364               25                 5                  38           0   
94177               19                 6                  31           0   
64517               14                 2                  52           0   
31907               12                 2                  77           0   
8374                18                 6                  52           0   

       number_outpatient  DXHypertension  number_diagnoses  ...  age_20-30)  \
47337                  0               0                 9  ...           0   
82295                  0               0                 7  ...           0   
44783                  0               0                 9  ...           0   
84950                  1               1                 9  ...           0   
67971                  0               0                 9  ...           0   
...                  ...             ...               ...  ...         ...   
60364                  0               0                 9  ...           0   
94177                  5               0                 9  ...           0   
64517                  0               1                 6  ...           0   
31907                  0               0                 9  ...           0   
8374                   0               0                 5  ...           0   

       admission_type_id  age_0-10)  DXFluid  age_80-90)  max_glu_serum_300  \
47337                  3          0        0           0                  0   
82295                  2          0        0           1                  0   
44783                  1          0        0           0                  0   
84950                  2          0        0           0                  0   
67971                  3          0        0           0                  0   
...                  ...        ...      ...         ...                ...   
60364                  1          0        1           0                  0   
94177                  1          0        0           0                  0   
64517                  5          0        0           0                  0   
31907                  6          0        0           0                  0   
8374                   3          0        0           0                  0   

       DXPneumonia  A1Cresult_Norm  A1Cresult_8  metformin_No  
47337            0               0            0             1  
82295            0               0            0             1  
44783            0               0            0             1  
84950            0               0            0             1  
67971            0     

In [5]:
y_train.value_counts()

1    7856
0    7856
Name: readmitted30, dtype: int64

In [6]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler()

In [7]:
X_train_scale = scaler.transform(X_train)
X_test_scale = scaler.transform(X_test)

In [8]:
from sklearn import svm

In [9]:
params = {"C": np.arange(1, 100, 0.2), 'gamma': [0.0001,0.001,0.01,0.1,1], 'class_weight': ['balanced', None]}

In [10]:
svc1 = sk.svm.SVC(kernel='rbf', random_state=0)

In [11]:
svc1_rs = sk.model_selection.RandomizedSearchCV(svc1, params, cv = 5, scoring = 'roc_auc', n_jobs = -1, verbose = 0)

In [12]:
svc1_rs.fit(X_train_scale, y_train)

RandomizedSearchCV(cv=5, estimator=SVC(random_state=0), n_jobs=-1,
                   param_distributions={'C': array([ 1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,  2.6,  2.8,  3. ,
        3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,
        5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,
        7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,
        9.8, 10. , 10.2, 10.4, 10.6, 10.8, 11. , 11.2, 11.4, 11.6, 11.8,
       12. , 12.2, 12.4, 12.6, 12.8, 13. , 13.2, 13...
       89. , 89.2, 89.4, 89.6, 89.8, 90. , 90.2, 90.4, 90.6, 90.8, 91. ,
       91.2, 91.4, 91.6, 91.8, 92. , 92.2, 92.4, 92.6, 92.8, 93. , 93.2,
       93.4, 93.6, 93.8, 94. , 94.2, 94.4, 94.6, 94.8, 95. , 95.2, 95.4,
       95.6, 95.8, 96. , 96.2, 96.4, 96.6, 96.8, 97. , 97.2, 97.4, 97.6,
       97.8, 98. , 98.2, 98.4, 98.6, 98.8, 99. , 99.2, 99.4, 99.6, 99.8]),
                                        'class_weight': ['balanced', None],
                         

In [13]:
svc1_rs.best_params_

{'gamma': 0.001, 'class_weight': 'balanced', 'C': 14.199999999999998}

In [14]:
svc1_rs.best_estimator_

SVC(C=14.199999999999998, class_weight='balanced', gamma=0.001, random_state=0)

In [15]:
y_pred1 = svc1_rs.best_estimator_.predict(X_test_scale)

In [16]:
sk.metrics.confusion_matrix(y_test, y_pred1)

array([[19244,  7291],
       [ 1765,  1548]])

In [17]:
sk.metrics.roc_auc_score(y_test, y_pred1)

0.596240526795135

In [18]:
sk.metrics.accuracy_score(y_test, y_pred1)

0.6965960868399893

In [19]:
print(sk.metrics.classification_report(y_test, y_pred1))

              precision    recall  f1-score   support

           0       0.92      0.73      0.81     26535
           1       0.18      0.47      0.25      3313

    accuracy                           0.70     29848
   macro avg       0.55      0.60      0.53     29848
weighted avg       0.83      0.70      0.75     29848



In [20]:
y_pred1_train = svc1_rs.best_estimator_.predict(X_train_scale)

In [21]:
sk.metrics.accuracy_score(y_train, y_pred1_train)

0.6155804480651731

In [22]:
sk.metrics.roc_auc_score(y_train, y_pred1_train)

0.6155804480651732

In [23]:
sk.metrics.confusion_matrix(y_train, y_pred1_train)

array([[5833, 2023],
       [4017, 3839]])

In [21]:
print(sk.metrics.classification_report(y_train, y_pred1_train))

              precision    recall  f1-score   support

           0       0.59      0.74      0.66      7856
           1       0.66      0.49      0.56      7856

    accuracy                           0.62     15712
   macro avg       0.62      0.62      0.61     15712
weighted avg       0.62      0.62      0.61     15712



In [8]:
params = {"C": np.arange(1, 100, 0.2)}

In [7]:
svc2 = sk.svm.SVC(kernel = 'linear', random_state=0)

In [9]:
svc2_rs = sk.model_selection.RandomizedSearchCV(svc2, params, cv = 5, scoring = 'roc_auc', n_jobs = -1, verbose = 0)

In [10]:
svc2_rs.fit(X_train_scale, y_train)

RandomizedSearchCV(cv=5, estimator=SVC(kernel='linear', random_state=0),
                   n_jobs=-1,
                   param_distributions={'C': array([ 1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,  2.6,  2.8,  3. ,
        3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,
        5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,
        7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,
        9.8, 10. , 10.2, 10.4, 10.6, 10.8, 11. , 11.2, 11.4, 11.6, 11.8,
       12. , 12.2, 12.4, 12.6,...
       84.6, 84.8, 85. , 85.2, 85.4, 85.6, 85.8, 86. , 86.2, 86.4, 86.6,
       86.8, 87. , 87.2, 87.4, 87.6, 87.8, 88. , 88.2, 88.4, 88.6, 88.8,
       89. , 89.2, 89.4, 89.6, 89.8, 90. , 90.2, 90.4, 90.6, 90.8, 91. ,
       91.2, 91.4, 91.6, 91.8, 92. , 92.2, 92.4, 92.6, 92.8, 93. , 93.2,
       93.4, 93.6, 93.8, 94. , 94.2, 94.4, 94.6, 94.8, 95. , 95.2, 95.4,
       95.6, 95.8, 96. , 96.2, 96.4, 96.6, 96.8, 97. , 97.2, 97.4, 97.6,
       97.8, 98

In [11]:
svc2_rs.best_params_

{'C': 15.799999999999997}

In [12]:
svc2_rs.best_estimator_

SVC(C=15.799999999999997, kernel='linear', random_state=0)

In [13]:
y_pred2 = svc2_rs.predict(X_test_scale)

In [14]:
sk.metrics.confusion_matrix(y_test, y_pred2)

array([[20235,  6300],
       [ 1951,  1362]])

In [15]:
print(sk.metrics.classification_report(y_test, y_pred2))

              precision    recall  f1-score   support

           0       0.91      0.76      0.83     26535
           1       0.18      0.41      0.25      3313

    accuracy                           0.72     29848
   macro avg       0.54      0.59      0.54     29848
weighted avg       0.83      0.72      0.77     29848



In [16]:
y_pred2_train = svc2_rs.predict(X_train_scale)

In [17]:
print(sk.metrics.classification_report(y_train, y_pred2_train))

              precision    recall  f1-score   support

           0       0.57      0.77      0.66      7856
           1       0.65      0.42      0.51      7856

    accuracy                           0.60     15712
   macro avg       0.61      0.60      0.59     15712
weighted avg       0.61      0.60      0.59     15712



In [18]:
from sklearn.naive_bayes import MultinomialNB

cnb = MultinomialNB()
cnb.fit(X_train, y_train)
y_cnb = cnb.predict(X_test)

In [19]:
cnb.score(X_test, y_test)

0.6700951487536854

In [20]:
print(sk.metrics.classification_report(y_test, y_cnb))

              precision    recall  f1-score   support

           0       0.91      0.69      0.79     26535
           1       0.16      0.48      0.24      3313

    accuracy                           0.67     29848
   macro avg       0.54      0.59      0.52     29848
weighted avg       0.83      0.67      0.73     29848

